# Generated by Django 2.0.6 on 2018-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_one',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_one_rank',
            new_name='away_team_rank_change',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_one_rank_change',
            new_name='away_team_rating_change',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_one_rating',
            new_name='away_team_resulting_rank',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_one_rating_change',
            new_name='away_team_resulting_rating',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_one_score',
            new_name='away_team_score',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_two_rank',
            new_name='home_team_rank_change',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_two_rank_change',
            new_name='home_team_rating_change',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_two_rating',
            new_name='home_team_resulting_rank',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_two_rating_change',
            new_name='home_team_resulting_rating',
        ),
        migrations.RenameField(
            model_name='rawmatch',
            old_name='team_two_score',
            new_name='home_team_score',
        ),
        migrations.RemoveField(
            model_name='rawmatch',
            name='team_two',
        ),
        migrations.AddField(
            model_name='rawmatch',
            name='home_advantage',
            field=models.BooleanField(default=False),
        ),
    ]
